name: budgety
description: "Eine Haushaltsbuch-App zur Verwaltung von Einnahmen und Ausgaben."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Sprachunterstützung für deutsche Texte im Kalender etc.
  flutter_localizations:
    sdk: flutter

  # Auf Version 0.20.2 aktualisiert, passend zum aktuellen Flutter SDK
  intl: ^0.20.2
  
  # Persistente Speicherung
  shared_preferences: ^2.3.5
  
  # Diagramme
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true